[book]
authors = ["Karolis VyÄius"]
language = "en"
multilingual = false
src = "src"
title = "Developers Handbook"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/AplinkosMinisterija/developer-handbook"
edit-url-template = "https://github.com/AplinkosMinisterija/developer-handbook/edit/main/{path}"
